// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWyNsyZwMQc3pVxJ-F2u6R7u76Vi2BKXk',
    appId: '1:633796790616:web:edaea231335219d7233d2d',
    messagingSenderId: '633796790616',
    projectId: 'ticketing-65ba5',
    authDomain: 'ticketing-65ba5.firebaseapp.com',
    storageBucket: 'ticketing-65ba5.firebasestorage.app',
    measurementId: 'G-SP4S6PKDPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOxf0_aV4Q9epJbZMoKYQ5csHwiu14sLo',
    appId: '1:633796790616:android:d6d97fc570aebb9e233d2d',
    messagingSenderId: '633796790616',
    projectId: 'ticketing-65ba5',
    storageBucket: 'ticketing-65ba5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChB5nVLCZsoLG2Szlyl1_hEPczj3fb_QA',
    appId: '1:633796790616:ios:e4fb934173376ce8233d2d',
    messagingSenderId: '633796790616',
    projectId: 'ticketing-65ba5',
    storageBucket: 'ticketing-65ba5.firebasestorage.app',
    iosBundleId: 'com.example.ticketingApp',
  );
}
